name: bay_search_books
description: A new Flutter application.

dependencies:
  flutter:
    sdk: flutter

  http:
  cached_network_image:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/